### ISSUE TITLE
Allow for matches if the sizes are identical or within a small variance even if the files have a different file tree

### ISSUE THREAD

**Issue by newadventure079** [mmgoodnow/cross-seed#160]
For certain TV seasons, some people will name the top folder a different name than other release groups will, even tho the files in the folders are identical.  Other times, both folders are identical except for some subtitle files.

In either of the above cases, the message `it has a different file tree` is shown and the pack is not considered a match.

It would be nice if the folder size was identical or within some size variance (#157), and the file tree was different, if the program would consider than a match.  The user can then setup symlinks to the differently named folder and then cross seed.

This would be an optional flag or even some additional text displayed in the output since not every person would be interested in this.  

I've missed some cross seeding opportunities because one person named the folder `Show xxx Season 1` and other named it `Show xxx season 1`, which caused the `it has a different file tree` message to be shown, even tho the files within the pack were identical

**Comment by mmgoodnow** [comment]
This is out of scope for this project. Partly because I do not want to encourage uploaders to do these kinds of renames. Cross-seeding is already a micro-optimization so this will never be necessary

**Comment by hell001** [comment]
Hello @mmgoodnow,

Commenting in this issue because I think it might be related.

Based on the above answer, this tool will reject matches for situations where people remove base folders when sharing to other sources.

For example:

File tree from the main source:
`MovieName/MovieName.mkv`

File tree from reuploads from other sources:
`MovieName.mkv`

This scenario will produce the different file tree error for literally thousands of torrents by the famous Framestor because non-BHD trackers remove the base folder.. so ironically we can't even cross seed from the torrent where the content originated from. Some places even have rules to remove the base folder. Is it possible when matching file trees to consider that the top level folder may or may not be present? Even if as a config? Otherwise I'm not sure how to work around this.

**Comment by mmgoodnow** [comment]
It's in progress, but until then I'd consider that a Framestor problem. They're submitting uploads that don't work well with the rest of the community.

**Comment by hell001** [comment]
@mmgoodnow I can agree with that. Glad to hear that there is something in the works. Is it currently part of any branches? Unfortunately I don't know TypeScript, although it kind of reminds me of C#, otherwise I would try to contribute myself. Let me know if there's a way I can follow the progress of this, or if there's an ETA!

**Comment by zakkarry** [comment]
I second, or third, this feature request, this has also caused me issues where if nfo files, mainly, had been ignored, and after recheck downloaded, I would have cross-seeded. a 4KB file prevented seeding :(

I hope this will be considered.

**Comment by Greatdane** [comment]
I seem to have this issue as well, and it feels like a bug? 

For example, the original torrent for this was just a file named `Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv`, but when searching in cross-seed, I get the following response;

```
2024-01-26 10:51:21 [36mverbose[39m: [decide] Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv - no match for TorrentLeech torrent Migration 2023 1080p WEB-DL DDP5 1 Atmos H 264-FLUX - it has a different file tree
2024-01-26 10:51:31 [36mverbose[39m: [decide] Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv - no match for HDBits torrent Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX - it has a different file tree
2024-01-26 10:51:39 [36mverbose[39m: [decide] Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv - no match for MoreThanTV torrent Migration.2023.1080p.WEB-DL.DDPA5.1.H.264-FLUX - it has a different file tree
2024-01-26 10:51:59 [36mverbose[39m: [decide] Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv - no match for Blutopia (API) torrent Migration 2023 1080p MA WEB-DL DD+ 5.1 Atmos H.264-FLUX - it has a different file tree
```

I don't understand how we get `it has a different file tree` when its just a file on its own (both the original torrent file and the ones it failed to match), the only difference seems to be the torrent file name. Is there no way we can control this in config? These above 4 results should all inject succesfully but they do not 🤔

**Comment by zakkarry** [comment]
I'm not sure where you originating torrent comes from, but the Blu release is MA, and yours doesn't appear to have that tag/source.

The others I can't comment on since not knowing the torrents themselves, but you can run `cross-seed diff` (https://www.cross-seed.org/docs/reference/utils#cross-seed-diff) and see why they are different.

If you want to do this by size, i suggest you look into the matchmode setting (https://www.cross-seed.org/docs/basics/options#matchmode)

The docs have this and much more covered in detail.

**Comment by Greatdane** [comment]
TIL `cross-seed diff`, thanks!

That showed a different file size. Would be great if this was noted in the verbose logs so its clearer to see the reason why something was not added. 

```
AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  {
    files: [
      {
+       length: 5397418467,
-       length: 5397420091,
        name: 'Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv',
        path: 'Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv'
      }
    ],
+   length: 5397418467,
-   length: 5397420091,
    name: 'Migration.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv'
  }
    at diff (file:///usr/src/cross-seed/dist/diff.js:6:9)
    at Command.diffCmd (file:///usr/src/cross-seed/dist/diff.js:21:5)
    at async Command.parseAsync (/usr/src/cross-seed/node_modules/commander/lib/command.js:923:5)
    at async file:///usr/src/cross-seed/dist/cmd.js:232:1 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: [Object],
  expected: [Object],
  operator: 'deepStrictEqual'
}
```

**Comment by zakkarry** [comment]
If you can make an issue for this feature/enhancement I'd appreciate it...
