### ISSUE TITLE
Ignore files except .mkv

### ISSUE THREAD

**Issue by pablito7** [mmgoodnow/cross-seed#19]
Hi. Is it possible to ignore all files besides the movie itself? .nfo files are getting in the way of seraching for suitable torrents files.

**Comment by mmgoodnow** [comment]
Yeah. Right now I'm working on some verbose logging and testing, but after that (in a week or two) I plan to make the pre-filtering a lot less aggressive and maybe configurable. 

If you're code savvy, you could try removing these lines:

https://github.com/mmgoodnow/cross-seed/blob/2e4656d76242e61f375f13c59a71d97af5944403/src/preFilter.js#L14-L17

I don't know how well that will work, if at all. There's also code [here](https://github.com/mmgoodnow/cross-seed/blob/2e4656d76242e61f375f13c59a71d97af5944403/src/decide.js#L5-L17) that makes sure that the file trees are identical when it's assessing a Hackett search result, so if one torrent has nfos and another doesn't, it'll still reject the search result. So you might have to change that code too but it would be more involved.


Remember to clear your cache if you do these changes.

**Comment by mmgoodnow** [comment]
I added an option in configuration / CLI flag that bypasses the pre-filter stage in `v1.6.0`. This means that it will no longer decide not to search for a torrent just because of its contents. 

However, it's likely that your success will be limited because the existence of those small files is liable to vary across trackers, so the search results will just get rejected later down the pipeline. 

I might circle back to do fuzzy matching at some point in the future to try to solve this, but right now I'm not sure that's the direction I want to take with this tool.
