### ISSUE TITLE
IRC monitoring support

### ISSUE THREAD

**Issue by keldian** [mmgoodnow/cross-seed#204]
Just throwing this out there. Perhaps some integration could be added with one of the below projects, since they are becoming quite a popular way to fetch new torrents.

https://gitlab.com/cloudb0x/trackarr
https://github.com/autobrr/autobrr

I did notice from https://github.com/mmgoodnow/cross-seed/issues/13 that RSS is now planned. Either of these options will make a great addition.

**Comment by mmgoodnow** [comment]
Agreed. This should be a relatively simple addition after #13 is implemented. Currently we have a way to search for cross-seeds given a source torrent but for RSS and IRC it's the other way around - given a potential cross-seed, search through the torrents we have on hand to see if it's a match for something we already have

**Comment by mmgoodnow** [comment]
@keldian do either of these have an API spec that isn't tightly coupled to Sonarr/Radarr? I wouldn't really want to have to support both with custom code. Ideally there's a standardized spec that they both conform to

**Comment by ludviglundgren** [comment]
Saw autobrr mentioned here so thought I should chime in. I've added a basic webhook action to autobrr which can run a post to the webhook endpoint of cross-seed when a torrent has been matched and added.

https://github.com/autobrr/autobrr/pull/184

Currently only in develop, but will make a release soon. Need to write some docs for it, but if you wanna try it out:

1. Add a new acton of type `webhook` to a filter
2. Url is probably `http://localhost:PORT/api/webhook`
3. Data
```json
{ "name": "{{ .TorrentName }}" }
```

Like:
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/16375387/159160029-baf405f4-ed0c-472d-a6c6-ba8cb50f7dce.png">

**Comment by mmgoodnow** [comment]
@ludviglundgren this would technically work but it will perform a whole bunch of unnecessary work (triggering a search). I can probably stand up an endpoint that can, given a name and download link, do this properly in a day or two. Would you mind waiting for that?

**Comment by ludviglundgren** [comment]
I see! I have a couple of users already doing that, and I think it's the desired behavior to search.  But if thats wrong and you can build something better suited then I'm all for it. Since this is just a webhook it's flexible.

@KyleSanderson you are one of the users of this, maybe would be good to hear what you want from this feature 😄

**Comment by mmgoodnow** [comment]
@ludviglundgren does autobrr have access to torrent length?

**Comment by mmgoodnow** [comment]
Reading the docs, it seems like it's already downloaded the torrent by the time it would hit the cross-seed webhook. So i guess so? but not sure. Does it snatch every torrent it sees in an announce channel before deciding what to do with it?

**Comment by ludviglundgren** [comment]
Unlike autodl-irssi it doesn't snatch more torrents than necessary. And that depends on the filters, and the announces. Like if the announce doesn't have size and there's filter for it, it will download the file and try to match against that.

So the actions are only ran when it's considered a match, and downloading. So yes, we can send the size, infohash etc. And link to file on disk if you want to parse things yourself.

But the way it's setup with actions might not be the best way from autobrr's side either. Maybe it should be more like what the arr's does with notifications/events and only send on the event of "matched and downloaded".

It's in my roadmap/plans for RSS support and some form of cross-seeding as well but giving people the option to use external tools is quite important.

**Comment by mmgoodnow** [comment]
> So the actions are only ran when it's considered a match, and downloading

What do you mean by downloading? Like downloading the torrent's contents? Not sure I'm understanding properly, but that seems like it's not fully compatible with the cross-seeding model and may be too _late_ in the autobrr pipeline—in the case of the original/source torrent, that would be too early to search for cross-seeds because it won't be done yet. In the case of subsequent cross-seeds that get announced which you already have the data for, if it's already downloading, wouldn't that mean that it's clobbering the existing data and downloading twice?

What I'm envisioning for announce integration with cross-seed is that cross-seed has a webhook that can ingest announce events, look to see if it already has a torrent with the same name in its torrentDir, then run through the match checking procedure for the announced torrent and inject if successful. Doing it that way avoids running a whole search which would just rediscover what just got announced.

Here's what I'm thinking for API spec:

```http
POST /api/announce // maybe /api/autodl? not sure, mildly unfamiliar with autodl type stuff so I'd be open to suggestions here
Content-Type: application/json
{
  "guid": "string", // ideally the torrent's comments/listing url, would be for caching purposes
  "link": "string", // download link
  "size": "number",
  "title": "string",
  "tracker": "string" // this would probably just be for logging purposes
}
```

**Comment by KyleSanderson** [comment]
> @KyleSanderson you are one of the users of this, maybe would be good to hear what you want from this feature 😄

I'm treating cross-seed like sonarr - pump everything into it then relying on the tool to "do the right thing". As cross-seed is running in daemon mode (similar to sonarr), it's not necessarily correlated to release times on various trackers. As such, "later" units will be missed with the current deployment of either. Listening to IRC events from autobrr, and cross-seed being the intelligent query application to look at my client before querying Jackett is greatly beneficial.

In my opinion (with my specific configuration), it is inappropriate for cross-seed to add support for IRC or RSS as it's adding another point of configuration / filtering. This reason is precisely why I abandoned my ancient perl config in favour of people still around (and, fortunately still alive). Acting in this modular fashion (and having one single irc client) I'm fairly confident is what the majority of users would want as there's only one registered nick. I'm not looking to enter the bnc business.

Consolidating configuration is what's important to me, which I've reached. The only consumer of Jackett for me is cross-seed, and I'm OK with that because it's now the single configuration point for this.

Minimizing site load is also important, which is why having a single point of truth (like, posting the file contents as opposed to the url if autobrr already has it) is desirable as well as opposed to the proposed "link" design.

**Comment by mmgoodnow** [comment]
> I'm treating cross-seed like sonarr - pump everything into it then relying on the tool to "do the right thing"…Listening to IRC events from autobrr, and cross-seed being the intelligent query application to look at my client before querying Jackett is greatly beneficial.

I agree. I would also prefer that ideally, cross-seed receives these events ***before*** torrents get downloaded. Because in the vast majority of cases, cross-seed can rule out torrents from being matches solely by the names not matching. 

> As cross-seed is running in daemon mode (similar to sonarr), it's not necessarily correlated to release times on various trackers. As such, "later" units will be missed with the current deployment of either. 

Not sure I understand this part. What is a unit?

> In my opinion (with my specific configuration), it is inappropriate for cross-seed to add support for IRC or RSS as it's adding another point of configuration / filtering. This reason is precisely why I abandoned my ancient perl config in favour of people still around (and, fortunately still alive). Acting in this modular fashion (and having one single irc client) I'm fairly confident is what the majority of users would want as there's only one registered nick. I'm not looking to enter the bnc business.

I agree with this, to a degree. I definitely have zero interest in implementing low-level IRC announce support directly into cross-seed. As I posted above, my ideal solution just involves ingesting HTTP requests sent by other apps (autobrr or trackarr). However, RSS comes for free with Torznab and provides several benefits over IRC because it allows the app to make sure it didn't miss any messages while the app was restarting or something. 

> Minimizing site load is also important, which is why having a single point of truth (like, posting the file contents as opposed to the url if autobrr already has it) is desirable as well as opposed to the proposed "link" design.

I mentioned this above, but to reiterate, this would be nice but I think it would be better overall if cross-seed receives these events before the torrents ever get snatched, at least on cross-seed's behalf. If they got snatched for some other reason, then maybe it's worth it. But if we're doing "pump everything into it then relying on the tool to do the right thing", then I think the lowest footprint can be achieved by the IRC client passing things along without snatching.

I can also make the `size` parameter optional so as not to require a snatch.

**Comment by mmgoodnow** [comment]
There's also an argument to make that this entire process would be detrimental to tracker economies and making it widely available could be somewhat irresponsible. I'd be interested in hearing opinions on that. 

The rationalization I keep making in my head is that it improves retention, which is probably more important than economy. However I also realize that having several people cross-seeding as soon as torrents are announced could disincentivize uploading because the uploader doesn't even necessarily get to a 1.00 upload:size ratio.

**Comment by KyleSanderson** [comment]
> There's also an argument to make that this entire process would be detrimental to tracker economies and making it widely available could be somewhat irresponsible. I'd be interested in hearing opinions on that.
> 
> The rationalization I keep making in my head is that it improves retention, which is probably more important than economy. However I also realize that having several people cross-seeding as soon as torrents are announced could disincentivize uploading because the uploader doesn't even necessarily get to a 1.00 upload:size ratio.

What went through this with better.php. Better was a tool that was part of the site that would allow you to see which (perfect) FLACs did not have aac/ogg/mp3 variants. As a result, people started automating this process which greatly increased the availability of content. However, after a while it was realized that people were racing on better, which also meant that the original uploader, could potentially miss out on their own variant uploads. This happened well more than a handful of times, to the point now that even with creative commons video uploads now over a decade later people go from the lowest quality possible all the way back to the source.

Ultimately, it comes down to the source of the content. If people are still using ScarS, the content almost certainly came from somewhere else. ScT was hilarious at the end because they were sourcing from SCC. Anyway, the source uploader is still credited with the post, but that ubuntu iso everyone can help with the availability of it, which lessens their system load, which allows for the more sharing of content, which was the entire idea behind BT to begin with. And that guy with the original content? Easy, post in all the applicable areas at the same time, beat the couriers.  This issue exists with or without cross-seed, which cross-seed doesn't change the paradigm.

Opinions are like assholes though, so I'm happy to hear the coin flip.

**Comment by keldian** [comment]
> Not sure I understand this part. What is a unit?

I could be mistaken but I think he means torrent uploads that are cross-seed matches. The scenario in question being one where arrs monitor multiple indexers for a wanted release, and inevitably fetch it from the tracker where it's uploaded first. A later unit would be the same release uploaded to another tracker... later (too late for daemon mode to catch).

**Comment by mmgoodnow** [comment]
Alpha support in v3.4.0. It's not documented yet but you can use my comment above as the spec.
