### ISSUE TITLE
what makes a torrent suitable to search?

### ISSUE THREAD

**Issue by scr44tch** [mmgoodnow/cross-seed#21]
Found 135 torrents, 91 suitable to search for matches

what makes a torrent suitable?
why not search all?
i have: includeEpisodes: true,

**Comment by mmgoodnow** [comment]
The latest update now has a `-v` flag that you can specify on the command line to see more information about this. I'm also planning on adding functionality to search for all.

**Comment by mmgoodnow** [comment]
I added an option in configuration / CLI flag that bypasses the pre-filter stage in v1.6.0. This means that it will no longer decide not to search for a torrent just because of its contents. If you're trying to use `cross-seed` for music, this will help a lot. 

If you're trying to use it for video torrents with NFO files, it's likely that your success will still be limited because the existence of those small files is liable to vary across trackers, so the search results will just get rejected later down the pipeline.

I might circle back to do fuzzy matching at some point in the future to try to solve this, but right now I'm not sure that's the direction I want to take with this tool.
