### ISSUE TITLE
Add documentation site

### ISSUE THREAD

**Issue by mmgoodnow** [mmgoodnow/cross-seed#250]
- [x] how to set up on-download-finished
- [x] how to set up RSS
- [x] how to set up periodic searches
- [x] how to fill out configuration file
- [x] config file examples
- [x] Architecture
- [x] Actions
- [x] Notifications
- [x] API
- [x] Options
- [x] Daemon mode
- [x] Search mode
- [x] Utils
- [ ]

**Comment by BastionNtB** [comment]
I would add a section on example scenarios. I want to set this up, but I have no idea where to start or how to hook it up to anything. Mainly because I can't seem to figure out how to actually envision this being put together to do what it's designed to do.

It seems absolutely perfect for what I want, but yeah, I'm struggling on the implementation. I'm pretty good at documentation, I could probably help out once I figure it out though.
