### ISSUE TITLE
Cross-seed Save torrents that don't cross-seed properly

### ISSUE THREAD

**Issue by Drazzilb08** [mmgoodnow/cross-seed#76]
With the usage of inject I've ran across a few torrents that aren't 100% the same (like before). 
Rather than hunting down the faulty torrent on their given site would there a be a way for cross-seed to register a torrent that is in the cross-seed category that is paused and not started (something along those lines) and then take that torrent (and a copy of the original torrent file) and save it to a dir for further analysis.

**Comment by mmgoodnow** [comment]
To clarify, you're saying that you'd like cross-seed to occasionally peer into your torrent client to find torrents that were successfully injected but have since been stopped due to missing files?

This doesn't really sound like a job for cross-seed. With a little bit of python you'd probably be able to whip up a quick script to do that, though. 

What I might be able to do is more checking on each file matching before injecting, though I'm not really sure what would be going wrong. Last time it turned out to be a pretty cool bug (with the 0-length paths) so I'll definitely stay tuned!

**Comment by Drazzilb08** [comment]
Sounds good. The reason is with my massive list of torrents I come across torrents that don't start due to the folder structure being different (like we had before in the first issue I posted). In order to debug more effectively I have to find those two exact torrents on their respective trackers and crack them open to figure out what the is. I was thinking if cross-seed took that out of the equation might make finding those issues a bit easier/quicker.
