### ISSUE TITLE
[qbittorrent] omit categories from being searched

### ISSUE THREAD

**Issue by Drazzilb08** [mmgoodnow/cross-seed#95]
I have a trash category for torrents that I'm just waiting for their seed time/ratio to expire. I don't want cross-seed to look within that category and cross seed a torrent that is going to be removed soon anyways.

**Comment by mmgoodnow** [comment]
This'll be hard to do right now, but I'm hoping I can get the architecture to a place where it'll be easier at some point.

Currently we don't have that info at search time, because searching is completely driven by the torrent files themselves and we don't talk to qBittorrent until after matches have been found and we're trying to inject them.

**Comment by Drazzilb08** [comment]
As long as we can pin this and leave it as a future project I'm totally down for that. And as always love to test.

**Comment by mmgoodnow** [comment]
one thought is that once you're using daemon mode you can do this omission in the post-process shell script (i know it still doesn't support qBittorrent, haven't had much time lately 😞)

**Comment by mmgoodnow** [comment]
bundled into #210
